#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $NO_REPO == "Creminals" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1lvdW5nY2hyaXMxNTAvTm9v=" | base64 -d
    elif [[ $NOO_REPO == "Noo" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1lvdW5nY2hyaXMxNTAvTm9v=" | base64 -d
    elif [[ $NOO_REPO =~ $regex ]]
    then
        if [[ $NOO_REPO_BRANCH ]]
        then
            echo "${NOO_REPO}/archive/${NOO_REPO_BRANCH}.zip"
        else
            echo "${NOO_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1lvdW5nY2hyaXMxNTAvTm9v=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="No.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    NooPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $NooPATH
    echo "    Starting Creminal    "
    echo "
                          ─────────────╔╗───────────╔═╗     ╔╗────╔╗─
╔═╗╔╦╗╔═╗╔══╗╠╣╔═╦╗╔═╗─╔╗─║═╣     ║╚╗╔═╗║╚╗
║═╣║╔╝║╩╣║║║║║║║║║║║╬╚╗║╚╗╠═║     ║╬║║╬║║╔╣
╚═╝╚╝─╚═╝╚╩╩╝╚╝╚╩═╝╚══╝╚═╝╚═╝     ╚═╝╚═╝╚═╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
